# Generated by Django 4.2.15 on 2024-09-07 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('unNum', models.CharField(blank=True, max_length=200)),
                ('designation', models.CharField(max_length=200)),
                ('ftm', models.CharField(blank=True, max_length=3)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('idnum', models.CharField(blank=True, max_length=200)),
                ('cell', models.CharField(blank=True, max_length=200)),
                ('homenum', models.CharField(blank=True, max_length=200)),
                ('dob', models.DateTimeField(blank=True, null=True)),
                ('position', models.CharField(blank=True, max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manplan.employee')),
            ],
        ),
    ]
