# Generated by Django 4.2.15 on 2024-09-07 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manplan', '0002_remove_employee_position_schedule_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='shift',
            field=models.CharField(blank=True, max_length=1),
        ),
    ]
