# Generated by Django 4.2.15 on 2024-09-08 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manplan', '0003_employee_shift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='designation',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='employee',
            name='shift',
            field=models.CharField(max_length=1),
        ),
    ]
