# Generated by Django 4.2.15 on 2024-08-23 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift', models.CharField(blank=True, max_length=3)),
                ('date', models.DateTimeField()),
                ('cycle', models.CharField(blank=True, max_length=3)),
            ],
        ),
    ]
