# Generated by Django 4.2.15 on 2024-08-23 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cycle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift', models.CharField(max_length=3)),
            ],
        ),
        migrations.AlterField(
            model_name='cycle',
            name='shift',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cycle.shift'),
        ),
    ]
