# Generated by Django 4.2.15 on 2024-08-23 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cycle', '0003_remove_cycle_shift_cycle_shift'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cycle',
            name='shift',
        ),
        migrations.AddField(
            model_name='cycle',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cycle.shift'),
        ),
    ]
