# Generated by Django 4.2.15 on 2024-08-24 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycle', '0004_remove_cycle_shift_cycle_shift'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cycle',
            name='cycle',
        ),
        migrations.RemoveField(
            model_name='cycle',
            name='shift',
        ),
        migrations.AddField(
            model_name='cycle',
            name='aShift',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AddField(
            model_name='cycle',
            name='bShift',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AddField(
            model_name='cycle',
            name='cShift',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AddField(
            model_name='cycle',
            name='dShift',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AddField(
            model_name='cycle',
            name='eShift',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AddField(
            model_name='cycle',
            name='fShift',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AddField(
            model_name='cycle',
            name='team1',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AddField(
            model_name='cycle',
            name='team2',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AddField(
            model_name='cycle',
            name='team3',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AddField(
            model_name='cycle',
            name='team4',
            field=models.CharField(blank=True, max_length=1),
        ),
    ]
