# Generated by Django 5.1 on 2024-08-14 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_alter_profile_dob"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="initals",
            new_name="initials",
        ),
    ]
